version: '3.8'

services:
  video-query:
    build: .
    container_name: video-query
    volumes:
      - ./app/data:/app/data
      - ./app/index:/app/index
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    entrypoint: ["/entrypoint.sh"]
    command: [] 